stages:
  - test
  - build
  - deploy

verify:
  stage: test
  tags:
    - maven
  script:
    - echo "Building project with maven"
    - mvn verify -DskipTests
 
build:
  stage: build
  tags:
    - maven
  script:  
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
      
deploy:
    stage: deploy
    tags:
    - maven
    script:
        - rsync -chavzP --stats --rsync-path="echo smart@123 | sudo -Sv && sudo rsync" target/smart-health-1.0.0.jar /opt/smarthealth/latest/smart-health-1.0.0.jar
        - service smarthealth-app restart
    
    only:
        - master
cache:
  paths:
    - ~.m2/repository/