stages: 
  - build
  - staging
  - deploy

build:
  stage: build
  tags:
    - maven
  script:  
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
      
deploy_dev:
    stage: staging
    tags:
    - maven
    script:
        - sudo rsync -rav -e --stats target/smart-health-1.0.0.jar /opt/smarthealth/latest/smart-health-1.0.0.jar
        - sudo chmod 775 /var/log/smarthealth-app.log
        - sudo service smarthealth-app restart
       
deploy_prod:
    stage: deploy
    tags:
    - maven
    script:
        - sshpass -V
        - sshpass -p "$QA_SERVER_PASSWORD" sudo rsync -rav -e --stats target/smart-health-1.0.0.jar smart@192.180.4.135:/opt/smarthealth/latest/smart-health-1.0.0.jar
        - sshpass -p "$QA_SERVER_PASSWORD" sudo service smarthealth-app restart
    
    only:
        - master
cache:
  paths:
    - ~.m2/repository/