# maven_build:
#  script: mvn verify

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:  
    - mvn verify -DskipTests

build:
  stage: build
  script:  
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

variables:
  # MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    
before_script:
    # - apt update && apt install -y maven
    
deploy:
    stage: deploy
    script:
        - mvn clean
        - mvn package -DskipTests
        - cp target/smart-health-1.0.0.jar /opt/smarthealth/latest/smart-health-1.0.0.jar
        - sudo service smarthealth-app restart
    
    only:
        - master
cache:
  paths:
    - .m2/repository/
