image: maven:latest

variables: 
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.skip.test=true"
  
cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.skip.test=true package
    
deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master

